---
swagger: '2.0'
info:
  version: 0.0.2
  title: BlockMint-node
  description: Backend for BlockMint project, for reddis part
  license: { name: MIT,  url: https://opensource.org/licenses/MIT }
basePath: /
tags:
- { name: user, description: User related actions }
- { name: vpn list, description: VPN list operations }

paths:
  /user:
    post:
      summary: Save user key with given password and address. This api does not validate key
      tags: [ user ]
      consumes:
      - multipart/form-data
      parameters:
      - name: address
        in: formData
        required: true
        type: string
      - name: password
        in: formData
        required: true
        type: string
      - in: formData
        name: file
        type: file
      responses:
        200: { description: File uploaded, user and password stored in db }
  /user/{wallet}/info:
    get:
      summary: Get user info with given wallet
      tags: [ user ]
      parameters:
      - name: wallet
        in: path
        required: true
        type: string
      responses:
        200:
          description: Info about user
          schema:
            type: object
            properties:
              wallet: { type: string }
              password: { type: string }
        400: { description: Wallet not registered }
  /vpn:
    get:
      summary: Get list of vpn severs (urls)
      tags: [ vpn list ]
      responses:
        200:
          description: Returns list of urls
          schema: { type: array,  items: { type: string } }
    post:
      summary: Update list of vpn severs
      tags: [ vpn list ]
      parameters:
      - in: body
        name: body
        description: String list of urls
        schema: { type: array,  items: { type: string } }
      responses:
        200:
          description: Sever was updated successfully
