---
swagger: '2.0'
info:
  version: 0.0.2
  title: BlockMint-node
  description: Backend for BlockMint project, for reddis part
  license: { name: MIT,  url: https://opensource.org/licenses/MIT }
basePath: /
tags:
- { name: user, description: User related actions }
- { name: vpn list, description: VPN list operations }

paths:
  /user/{wallet}/info:
    get:
      tags: [ user ]
      parameters:
      - name: wallet
        in: path
        required: true
        type: string
      summary: Get user info with given wallet
      responses:
        200:
          description: Info about user
          schema:
            type: object
            properties:
              wallet: { type: string }
              password: { type: string }
        400: { description: Wallet not registered }
  /user/{password}:
    post:
      tags: [ user ]
      parameters:
      - name: password
        in: path
        required: true
        type: string
      summary: Create new wallet with password
      responses:
        200:
          description: Returns valid wallet
          schema:
            type: string
            properties:  { wallet: { type: string } }
  /vpn:
    get:
      tags: [ vpn list ]
      summary: Get list of vpn severs (urls)
      responses:
        200:
          description: Returns list of urls
          schema: { type: array,  items: { type: string } }
    post:
      parameters:
      - in: body
        name: body
        description: String list of urls
        schema: { type: array,  items: { type: string } }
      tags: [ vpn list ]
      summary: Update list of vpn severs
      responses:
        200:
          description: Sever was updated successfully
